apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: redmine:latest
        ports:
        - containerPort: 3000
        env:
        - name: REDMINE_DB_MYSQL
          value: mysql
        - name: REDMINE_DB_PASSWORD
          value: password_ejemplo
        - name: REDMINE_SECRET_KEY_BASE
          value: supersecretkey

