apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-pv-data
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/ubuntu/redmine-pv/redmine-data
