apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-pv-config
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/ubuntu/ldap-pv/data/slapd/config

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-pvc-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
