apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: openldap-ui
  name: openldap-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openldap-ui
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/ldap-openldap: "true"
        io.kompose.service: openldap-ui
    spec:
      containers:
        - env:
            - name: LDAP_ADMINS_GROUP
              valueFrom:
                configMapKeyRef:
                  key: LDAP_ADMINS_GROUP
                  name: ldap-env
            - name: LDAP_ADMIN_BIND_DN
              valueFrom:
                configMapKeyRef:
                  key: LDAP_ADMIN_BIND_DN

                  name: ldap-env
            - name: LDAP_ADMIN_BIND_PWD
              valueFrom:
                configMapKeyRef:
                  key: LDAP_ADMIN_BIND_PWD
                  name: ldap-env
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: LDAP_ADMIN_PASSWORD
                  name: ldap-env
            - name: LDAP_ADMIN_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: LDAP_ADMIN_USERNAME
                  name: ldap-env
            - name: LDAP_BASE_DN
              valueFrom:
                configMapKeyRef:
                  key: LDAP_BASE_DN
                  name: ldap-env
            - name: LDAP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: LDAP_DOMAIN
                  name: ldap-env
            - name: LDAP_IGNORE_CERT_ERRORS
              valueFrom:
                configMapKeyRef:
                  key: LDAP_IGNORE_CERT_ERRORS
                  name: ldap-env
            - name: LDAP_ORGANISATION
              valueFrom:
                configMapKeyRef:
                  key: LDAP_ORGANISATION
                  name: ldap-env
            - name: LDAP_READONLY_USER
              valueFrom:
                configMapKeyRef:
                  key: LDAP_READONLY_USER
                  name: ldap-env
            - name: LDAP_READONLY_USER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: LDAP_READONLY_USER_PASSWORD
                  name: ldap-env
            - name: LDAP_READONLY_USER_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: LDAP_READONLY_USER_USERNAME
                  name: ldap-env
            - name: LDAP_REQUIRE_STARTTLS
              valueFrom:
                configMapKeyRef:
                  key: LDAP_REQUIRE_STARTTLS
                  name: ldap-env
            - name: LDAP_TLS_VERIFY_CLIENT
              valueFrom:
                configMapKeyRef:
                  key: LDAP_TLS_VERIFY_CLIENT
                  name: ldap-env
            - name: LDAP_URI
              valueFrom:
                configMapKeyRef:
                  key: LDAP_URI
                  name: ldap-env
            - name: NO_HTTPS
              valueFrom:
                configMapKeyRef:
                  key: NO_HTTPS
                  name: ldap-env
            - name: PASSWORD_HASH
              valueFrom:
                configMapKeyRef:
                  key: PASSWORD_HASH
                  name: ldap-env
            - name: PHPLDAPADMIN_HTTPS
              valueFrom:
                configMapKeyRef:
                  key: PHPLDAPADMIN_HTTPS
                  name: ldap-env
            - name: PHPLDAPADMIN_LDAP_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: PHPLDAPADMIN_LDAP_HOSTS
                  name: ldap-env
            - name: SERVER_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: SERVER_HOSTNAME
                  name: ldap-env
          image: wheelybird/ldap-user-manager:v1.5
          name: openldap-ui
          ports:
            - containerPort: 80
              hostPort: 18080
              protocol: TCP
      restartPolicy: Always
